### ISSUE TITLE
Custom Command to Refresh or Restart MM?

### ISSUE THREAD

**Issue by dresch27** [Klettner/MM-Remote#14]
Great module!!
Under Custom Commands, under "Notification of mirror module" I'm confused about what to put in the Notification line and Payload line for Remote Action.
I thought it would be REMOTE_ACTION in Notification and REFRESH in Payload, but nothing happens. Unlike VOLUME_UP and VOLUME_DOWN, which work perfectly in the Notification line. 
Any help would be greatly appreciated.
Thanks again!

**Comment by Klettner** [comment]
Hi, thanks for your feedback.
Currently I'm using this endpoint: ``/api/notification/{:notification*}/{:p}`` of [the MMM-Remote-Controle API](https://ezeholz.com.ar/MMM-Remote-Control/#/API/) to send the custom commands to the mirror. I did some testing aleady and it seems like this endpoint only sends notifications to other modules and not to MMM-Remote-Controle itselfe (they have seperate endpoints for their own functions), hence REFRESH does not work but VOLUME_UP does work since it is not native to MMM-Remote-Controle. 
You could create an issue there and ask if this is expected behaviour or which syntax you need to use to make it work.

I also have the idea to include a new feature in an upcoming update, which would make it possible to write [endpoints](https://ezeholz.com.ar/MMM-Remote-Control/#/API/) in addition to notifications when ceating a custom command. 
Then you could essentially write: ``/refresh``  to refresh the MM screen or ```/monitor/off``` to turn the monitor off, into the __Notification of mirror module__ textfield.
What are your thoughts on this?

**Comment by dresch27** [comment]
Thanks for your response. Absolutely, making it possible to write MMM-Remote-Control endpoints would make it possible and very easy to create custom commands. Also, would it be possible to include or move the custom commands on the main screen of the app?   
Thanks again

**Comment by Klettner** [comment]
The custom commands are separated on purpose, because I wanted to prevent to have one cluttered view on which you have to scroll up and down to find commands. It is currently also not easily possible to add support for a feature which would let you choose where you want to add a custom command due to the architecture of the code. 

But if you want to try implementing such a feature feel free to create a pull request

**Comment by Klettner** [comment]
I have added this function in the current release. You can find more detailed instructions on how to use it in [wiki/custom-commands](https://github.com/Klettner/MM-Remote/wiki/Custom-Commands)
